### ISSUE TITLE
GeoCode Address Latitude and Longitude workflow issue 

### ISSUE THREAD

**Issue by anvesh07** [demianrasko/Dynamics-365-Workflow-Tools#178]
Workflow Tools 1.0.52.1 Dynamics 365 On Prem

I'm trying to update latitude and longitude for given address on Account Entity with help of Geocode Address workflow activity.

I have registered this workflow on creation/update address of account entity record.

When i have update address on the record, the above plugin runs and update latitude and longitude to 0.000.

I have created bing map key from bingmapportal.  On the Map view its showing correct pin
![image](https://user-images.githubusercontent.com/17505677/73387752-02a7b500-429f-11ea-9c74-4691590662ab.png)

PFA.
![image](https://user-images.githubusercontent.com/17505677/73387526-b2c8ee00-429e-11ea-901e-be84119fc7c7.png)

![image](https://user-images.githubusercontent.com/17505677/73387648-dc821500-429e-11ea-9d78-52d57934f18f.png)

**Comment by demianrasko** [comment]
Hi  @anvesh07 I just tested the last version of the solution in an online environment, and is working fine. and there is no changes since the first released version (1.0.34.0).
Please check if evrything is ok with the Bing Maps API call, you should be able to call to this URL from the onprem server: http://dev.virtualearth.net/REST/v1/Locations/

thanks!
