### ISSUE TITLE
Issue with Set Process Stage

### ISSUE THREAD

**Issue by EivionSW** [demianrasko/Dynamics-365-Workflow-Tools#3]
Sorry to bother you, but I seem to be having a problem with the "Set Process Stage".  I always get a "Business Process Error" when I attempt to run a workflow with the "Set Process Stage" step in it.  We are running Dynamics 365 on premise v 8.2.0.749, and I installed version 1.0.38.0 of your Workflow Tools.  In the configuration of the "Set Process Stage" step, I have the Record URL set of the same entity that the workflow is part of; the Business Process Flow of the same entity is selected in the "Process" field, and the Process Stage Name is the stage I want to change to.  The error details do not really help, but here they are...  
[ErrorDetails.txt](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/files/903889/ErrorDetails.txt)

Any ideas?

**Comment by demianrasko** [comment]
Hi EivionSW, I just tested on a Dynamics 365 environment and works fine.
check the documentation here: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Set%20Process%20Stage.md

and then check:
1) if the parameters are ok (please share)
2) Check if the Stage name (third parameter) is not the name you see in the process on the record form, it must be the name on the name on the BPF configuration: 
![image](https://cloud.githubusercontent.com/assets/18124945/24833146/a380a26e-1cc0-11e7-8991-9fd1bf135d95.png)

Hope this helps, otherwise, please share me more details.

regards!

**Comment by EivionSW** [comment]
Thanks for your reply…here are the details:

Properties of “Set Process Stage”
[cid:image001.png@01D2B1D8.4F26C980]

Business Process Flow: (the primary entity for the BPF is called “Education Benefit Application”
[cid:image002.png@01D2B1D8.4F26C980]

**Comment by demianrasko** [comment]
Hi EivionSW, I cannot see the images...

**Comment by EivionSW** [comment]
That’s okay, Demian…I’ve decided to go in a slightly different direction.  The “Set Process” works perfectly, and I can use this instead.  Thanks for your help!
