### ISSUE TITLE
Update Child records with Boolean value

### ISSUE THREAD

**Issue by tpickles1984** [demianrasko/Dynamics-365-Workflow-Tools#40]
Using latest version of Workflow tools as of today, and a 365 8.2 instance.

I've been trying to update a two option (Boolean) field on some child records, using the Update Child Records workflow action. I've tried to specify the value directly rather than referencing another field, but it always results in an error (casting type if I recall). I've tried specifying 1 & 0 as the values, yes & no, true & false, but I get the same error every time. Can anyone help with how I should configure the workflow to update a Boolean? Any help would be much appreciated!

**Comment by demianrasko** [comment]
hi tpickles1984, 
thanks for your message, I found a bug on this point, and I fixed in the last version 1.0.48.2.
Now you can include "1" for true and "0" for false.
I updated the documentation too: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Update%20Child%20Records.md

Thanks!

**Comment by tpickles1984** [comment]
That's great, thank you! I found it worked if I referenced a field which was Boolean, but this update will allow a much simpler solution. Great work!

**Comment by demianrasko** [comment]
Thanks for sharing and helping to improve the Tools for everyone :)
