### ISSUE TITLE
Solution Files for Dynamics CRM 2015

### ISSUE THREAD

**Issue by Rsilla** [demianrasko/Dynamics-365-Workflow-Tools#5]
Hi. Thank you for working on this solution.

I have need for the solution that will work on Dynamics CRM 2015 version, please direct me to a link with the compatible solution version.

Thank you.

**Comment by demianrasko** [comment]
Hi Rsilla, thanks forma tour Email.
I don't Support Dynamics CRM 2015 version since nov 2015. The last version for CRM 2015 is this one: https://msdyncrmworkflowtools.codeplex.com/releases/view/618692
But it have just a few features.

In the current version I just support the last 3 releases:  2016, 2016 Update 1 and Dynamics 365 (8.0, 8.1, 8.2).
 You cannot import these solutions in a CRM 2015 because there are some methods I use that not exists in that version.in any case, if you need a specific feature, all the code is available and open and you can use it and build the solution.

Thanks.

Demi an.
