### ISSUE TITLE
Adding attachments to email from appointment

### ISSUE THREAD

**Issue by GoSoli** [demianrasko/Dynamics-365-Workflow-Tools#53]
We use CRM on premise 8.2.2 and the Workflow Tools 1.0.49.0 (also tested before with 1.0.40.0).

I made a workflow which creates an email (regarding an opportunity) out of an appointment (also regarding to the same opportunity) and add users. That works.
But then I want to add all attachments of the appointment (attachments directly in the appointment, not with "Documents" which are saved on the Sharepoint server) with "Entity Attachment To Email". And that doesn't work. I don't get any attachments in the email. In my example is one pdf file.
The sending of the mail at the end is not yet in the workflow, because not necessary to test.
The steps and the detail of the attachment step are in the screenshot below.

For testing purposes I run the workflow as an on demand workflow in the appointment.
The reason of the workflow shall be the sending of a visit report to several internal persons.

Can you please tell me if my way should work or what is wrong in my definition. Thanks!

![image](https://user-images.githubusercontent.com/36201081/35902499-b9eba93a-0bdb-11e8-980c-ab9dc82f7229.png)

**Comment by demianrasko** [comment]
Hi GoSoli, 
In this case, "Entity Attachment To Email" only retrieved attacments from notes. In your case you are using the ActivityMimeAttachment files, so the workflow activity doesn't retrieve any document, because you didn't use Notes.
Now, on next version I'll publish today, I added a new parameter called "Retrieve ActivityMimeAttachment", and if you set it to "true", then it will retrieve the attachments from there and not from Notes.
hope this helps ;)

regards
