### ISSUE TITLE
Qualify Lead to Contact

### ISSUE THREAD

**Issue by smeranda** [demianrasko/Dynamics-365-Workflow-Tools#56]
### Expected behavior and actual behavior.
I'm trying to convert a lead to a contact.

### Steps to reproduce the problem (screenshots are really usefull)
In my workflow, I receive the following error at the 'Qualify Lead' step.

```
Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.QualifyLead]
[msdyncrmWorkflowTools (1.0.48.3): Qualify Lead]
Load CRM Service from context --- OK
LeadID=845af699-500c-e811-80cd-0e90f102a102


Error Message:

Unhandled Exception: Microsoft.Crm.CrmException: An error has occurred. Either the data does not exist or you do not have sufficient privileges to view the data. Contact your system administrator for help.
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.Execute(IExecutionContext context)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
```

A screenshot of the workflow step properties.
![screen shot 2018-02-12 at 3 18 39 pm](https://user-images.githubusercontent.com/302114/36120224-17d3ba30-1008-11e8-99be-88be81555ff8.png)

### CRM Version - online/onpremise - WorkflowTools version
Onpremise, Dynamics 2016

**Comment by demianrasko** [comment]
Does the user than trigger the workflow has permissions to update Leads,  and to create and read Contacts?

**Comment by demianrasko** [comment]
Check if this user can qualify thekead using the web interface or ifyou get there the same error that you get running the workflow

**Comment by smeranda** [comment]
Yes, the user has full permissions to update leads, and can create and read contacts. The user can qualify a lead using the web interface.

**Comment by demianrasko** [comment]
Hi smeranda, the error message syas something regarding security and privileges.
first try to execute the workflow as administrator.
second check if the user has this privileges:
Account Entity Privileges Required: Read, Create, Append, Append To

Lead Entity Privileges Requires: Read, Edit, Create, Append, Append To

Contact Privileges Required: Read, Create, Append, Append To

Opportunity Privileges Required : Read, Create, Append, Append To

Apart from this give Read access to Attribute Map, Customizations, Entity and Entity Map on the Customizations tab in the security role in order to successfully qualify a lead.

**Comment by smeranda** [comment]
Thanks @demianrasko, however I'm running the workflow as a system administrator with full rights. Alas, it must be an issue with my environment.

**Comment by donalmc** [comment]
smeranda - was the solution migrated from another instance? e.g. a Sandbox?
Check that there are no business rules that have a hard Guid reference.
Workflows will deactivate in these scenarios, if there are business rules with a Guid reference, they will still import as active.
I only suggest this because this happened to us last week and had us stumped for a few hours.
