### ISSUE TITLE
Import in Dynamics 365 not possible

### ISSUE THREAD

**Issue by wollmilchsau** [demianrasko/Dynamics-365-Workflow-Tools#61]
Can't upload the .zip package via solution -> import.
Getting an error message saying that the files "solution.xml", "customizations.xml" and "[Content_Types].xml" belong to an older dynamics crm 365 version.

(I'm using the cloud version.)

Any suggestions?

Thanks

Alex

**Comment by brf132** [comment]
What CRM version are you using?  If you are on 9.0, thats why it is failing.  You can find this in the Settings (Gear Icon) --> About Dynamics CRM.

I came here to see if anyone had asked about a 9.0 release for this tool, as I am about to upgrade my client to 9.0, but the latest version only supports 8.2

**Comment by brf132** [comment]
Sorry, it is Settings Gear > About.

Also, I just checked one of my other client environments that I have this solution installed on.  The WorkFlow Tools solution  is version  1.0.48.3, and it imported fine into my  D365 CRM 9.0.1.425 instance.

I need to double check if the workflow assemblies work on my 9.0 CRM instance or not.

**Comment by wollmilchsau** [comment]
Hi, 

strange, it's 9.0.1.425 here too (Version 1612).

**Comment by brf132** [comment]
Try to download the version I have, 1.0.48.3, and install that.

It seems to be working in my environments, though I haven't tested EVERY function.

**Comment by wollmilchsau** [comment]
Any hint where to get it?
Thx.

**Comment by brf132** [comment]
https://github.com/demianrasko/Dynamics-365-Workflow-Tools/releases


It's on the releases tab, scroll down.

**Comment by wollmilchsau** [comment]
Thx

**Comment by wollmilchsau** [comment]
The import was successful.
Thank you.

**Comment by brf132** [comment]
Glad it worked.  Let me know if you run into any issues using the functions, this will help me in my testing, too.

If I knew how to @demianrasko  (oh, I just figured it out), I would ask the Dev why the OLD version of the solution imports into CRM 9.0.xxxxx, but the NEW version will not import to 9.0.xxxx?

**Comment by demianrasko** [comment]
Hi guys, 
I'm still developing the solution in 8.2 because few things:
1) There is an issue in 9.0 with the groupin names,  and I cannot change them in 9.0.
2) if I develop in 9.0, I need to have another environment for 8.x... Right now if I develop in 8.2, I can export to 8.1, 8.0 and the 8.2 it should work fine in in 9.0. In this way I support 4 different versiones.  If I develop in 9.0, I can only support 9.0.

I don't really have time to maintain this solution in two different environments and versions and this is why I'm still on 8.2.

I really want to move forward to 9.0, and to include some new stuff that I don't have in 8.x, but if I move in that way,  I have to stop support previous versions. 

Maybe next 1 April with the next 9.x release if the momento to make the jump. 

Thanks a lot for your support and help;) 

Demia

**Comment by brf132** [comment]
Thanks for letting us know Demia!  This is an amazing tool, and I am very grateful that you have built it and allowed us to use it for free!

Just curious, why does the latest build not import into 9.0, but the previous build (the one I quoted in this Issue thread) imports fine?

Either way, I know to use the older version for 9.0 for now, and it seems to work for the most part.

Thanks again!!

**Comment by demianrasko** [comment]
I don't know,  it should work fine in 9.0.
I will check it to see if anything is wrong. 
Thabks

**Comment by wollmilchsau** [comment]
Hi guys,

1.0.48.3 worked fine for me.
I was able to run the 'Qualify Leads' workflow without issues.

Thank you very much!

**Comment by demianrasko** [comment]
Thanks!!!
