### ISSUE TITLE
Set Process Stage - traversedpath

### ISSUE THREAD

**Issue by sebastiensapet** [demianrasko/Dynamics-365-Workflow-Tools#79]
### Expected behavior and actual behavior.
Exemple with 
- bpf step1 -> step2 -> step3
- Records a initialized with bpf1, step1. 

I use the set process stage on record a to set it to the step 2

actual behavior : 
in records a : traversedpath = "step1 guid"
in bpf entity : traversedpath = "step1 guid, step2 guid"

Expected behavior 
in records a : traversedpath = "step1 guid, **step2 guid**"
in bpf entity : traversedpath = "step1 guid, step2 guid"

if i use the next stage button in the form, i get the complete traversedpath

### CRM Version - online/onpremise - WorkflowTools version
onpremise 8.2.1.342

thanks

**Comment by demianrasko** [comment]
Hi sebastiensapet, 
probbably I need to check the behaviors on this, because right now I'm just updating the "processid" and "stageid" of the record. Since the new versions has a different entity to manage the BPF instances, probabbly this is not working fine regarding paths.
In any case, this is something I have for next releases.

thanks
